import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import {SessionProvider} from "next-auth/react";
import {Toaster} from "react-hot-toast";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "AI Bot Vercel",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <SessionProvider>
            <div className="flex">
                <div className="bg-black text-gray-200 max-w-[250px] h-screen overflow-y-auto md:min-w-[220px]">
                    <Sidebar/>
                </div>
                <div className="bg-[#212121] flex-1 h-screen overflow-hidden relative text-gray-200">
                    <Header/>
                    {children}
                </div>
            </div>
        </SessionProvider>
        <Toaster
            position="top-right"
            toastOptions={{
                style: { background: "#000000", color: "#ffffff" },
            }}
        />
        </body>
        </html>
    );
}
